spring:
  application:
    name: viet-phuc-store
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        ssl:
          trust: smtp.gmail.com
server:
  port: 8081
  servlet:
    context-path: /nextrad/api